[OTA] Check that /system is mounted successfuly, and abort installation if not

diff --git a/app/src/main/scripts/update-binary b/app/src/main/scripts/update-binary
--- a/app/src/main/scripts/update-binary
+++ b/app/src/main/scripts/update-binary
@@ -55,6 +55,12 @@ else
   mount "/dev/block/bootdevice/by-name/system" "$MOUNT_POINT"
 fi
 
+if [ "$?" -ne "0" ]; then
+  echo -n -e "ui_print Failed to mount system partition at ($MOUNT_POINT)\n" > /proc/self/fd/$2
+  echo -n -e 'ui_print Installation cannot continue, exiting...\n' > /proc/self/fd/$2
+  exit 1
+fi
+
 rm -rf "${SYSTEM}/app/FDroid"*
 rm -rf "${SYSTEM}/priv-app/FDroid"*
 rm -rf "${SYSTEM}/app/F-Droid"*
